# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'capybara', '~> 3.36'
gem 'capybara-selenium', '~> 0.0.6'
gem 'nokogiri', '~> 1.12', '>= 1.12.5'
gem 'pry'
gem 'selenium-webdriver', '~> 4.1'
