# frozen_string_literal: true

source 'https://rubygems.org'

group :test do
  gem 'capybara', '~> 3.35', '>= 3.35.3'
  # gem 'chromedriver-helper', '~> 2.1', '>= 2.1.1'
  # gem 'selenium-webdriver', '~> 3.142', '>= 3.142.7'
end

ruby '2.6.3'
