# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :test do
  gem 'rspec', '~> 3.5'
  gem 'simplecov', require: false, group: :test
end

group :test, :development do
  gem 'pry'
  gem 'rubocop-rspec', require: false
end
