# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'capybara'
gem 'pry'
gem 'rspec'
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.7'
